### ISSUE TITLE
CustomerSecret question.

### ISSUE THREAD

**Issue by supsup** [dolbyio-samples/comms-sdk-web-getting-started#1]
How do you protect  'customerSecret' if it is in the .js file that is served from the website?

**Comment by FabienLavocat** [comment]
Look at the [Step 2 of the Create a Basic Audio Conference Application](https://dolby.io/developers/interactivity-apis/client-sdk/getting-started/create-a-basic-audio-conference-application#step-2-initialize-the-sdk-with-your-dolbyio-credentials), to protect your `customerKey` and `customerSecret`, you can use a backend server that will request the token (used by the Voxeet SDK) on the behalf of the client.
The [voxeet-io-web](https://github.com/voxeet/voxeet-io-web) repo does exactly that using a Node.JS backend.
