### ISSUE TITLE
unable to create/join conreference after the client token refreshed

### ISSUE THREAD

**Issue by allvoice-devteam** [dolbyio-samples/comms-sdk-web-getting-started#15]
after refreshing callback function of initializeToken called,
when user retry to create/join conreference,
the request seems using the initial token.
(as the request header shows me)

the https://session.voxeet.com/v1/conferences/create response is below
`
{type: "ErrorResponse", error_code: 89, error_reason: "Invalid_token",…}
error_code: 89
error_description: "Expired or invalid token"
error_reason: "Invalid_token"
type: "ErrorResponse"
with status 401`

I also made sure that my refreshing callback is returning the access token string of new one.

further more, VoxeetSDK.initializeToken function does not returning promise result
so that I can't use .then or .catch phrase.

**Comment by FabienLavocat** [comment]
Here is a simple code sample to get an access token from your own backend server (You might need to update the URL and add extra HTTP headers based on your requirements)

```javascript
const url = 'https://endpoint/to/get/token';
fetch(url)
  .then(d => d.json())
  .then(r =>
     VoxeetSDK.initializeToken(r.access_token, () => fetch(url).then(d => d.json().access_token));
  )
  .then(() => 
     VoxeetSDK.session.open({ name: "username" }).then(() => startYourApplication());
  );
```

Regarding the documentation, I have created an internal ticket to have it fixed.

**Comment by allvoice-devteam** [comment]
my backend <-> user workflow works fine as it returns a new access token

but problem occurs when it comes to call the sdk function after refreshed.
it is send with the initial(not refreshed) token and returned with status 401.

![error](https://user-images.githubusercontent.com/73815287/103623826-fb435e00-4f7b-11eb-980e-05213653b49d.PNG)

I think It might be necessary the sdk returns it's results to let me know It is refreshed with the new one rightly.

thank you.

**Comment by FabienLavocat** [comment]
@allvoice-devteam could you please share the code you use to call `VoxeetSDK.initializeToken`

**Comment by FabienLavocat** [comment]
With the following code, you will notice the 401 errors, but it is our way to detect when the token is expired. Once we get a message from our service saying the token is expired, we will execute the callback provided to the `VoxeetSDK.initializeToken` function to request a new access token. This callback must return the access token.

Try the following code:

```javascript
const consumerKey = 'YOUR_CONSUMER_KEY';
const consumerSecret = 'YOUR_COMSUMER_SECRET';
const tokenUrl = 'https://session.voxeet.com/v1/oauth2/token';
const expiresIn = 5; // seconds

const requestParams = {
  method: 'POST',
  headers: {
      'Cache-Control': 'no-cache',
      'Content-Type': 'application/x-www-form-urlencoded',
      'Authorization': 'Basic ' + btoa(consumerKey + ':' + consumerSecret)
  },
  body: `grant_type=client_credentials&expires_in=${expiresIn}`
};

fetch(tokenUrl, requestParams)
  .then(d => d.json())
  .then(jwt => {
    console.log('Received the following JWT', jwt)

    VoxeetSDK.initializeToken(jwt.access_token, () => {
      console.log('The token has expired, request new one');

      return fetch(tokenUrl, requestParams)
        .then(d => d.json())
        .then(jwt => {
          console.log('Received a new JWT token', jwt);
          return jwt.access_token;
        });
    });
  })
  .then(() => VoxeetSDK.session.open({ name: randomName }).then(() => initUI()));
```

The token expires after 5 seconds, so after you initialize the session, wait 5 seconds and start the conference. You will get the 401 error but immediately after, we will request a new token and the conference can start.

**Comment by allvoice-devteam** [comment]
my initializing code of client side is down below

    fetch(url, {})
      .then(data => data.json())
      .then(result => {
            console.log('token expires in:: '+result.expires_in);

            VoxeetSDK.initializeToken(result.access_token, () => {
              // This callback is called when the token needs to be refreshed.

              // Call the server to get the refreshed token
              fetch(url, {})
                  .then(data => data.json())
                  .then(result => {
                      console.log('received token:: ', result.access_token)
                      return result.access_token
                  });
            })
      })
      .then(() =>
          VoxeetSDK.session.open({name: randomName})
            .then(() => {
                enableUI('test-conference')
            })
      )

It also is working when a client wants to create/join a conference.

     joinButton.onclick = function () {
       if (roomInput !== undefined) {
          if (audioDeviceId.value) {
                constraints.audio.sourceId = audioDeviceId.value;
          }

            console.log(constraints);

            VoxeetSDK.conference.create({
                alias: confAlias,
                params: {
                    dolbyVoice: true
                }
            })
                .then((conference) => {
                    if(conference._isNew) {
                        console.log('conference created :: ' + conference.alias)
                    }

                    VoxeetSDK.conference.join(conference, {
                        constraints: constraints,
                        audio3D: true
                    })
                        .then((info) => {
                            ...

                        })
                        .catch(function (e) {
                            console.error(e);
                        })
                })
                .catch( err => {
                    console.log(err)
                })

        }
    }


and It keeps returning
create(401) -> token(200) -> create(401) -> ... and so on as the previous comment.

did I understood something wrong?

**Comment by FabienLavocat** [comment]
You are missing a `return`

```javascript
fetch(url, {})
  .then(data => data.json())
  .then(result => {
        console.log('token expires in:: '+result.expires_in);

        VoxeetSDK.initializeToken(result.access_token, () => {
          // This callback is called when the token needs to be refreshed.

          // Call the server to get the refreshed token
          return fetch(url, {})
              .then(data => data.json())
              .then(result => {
                  console.log('received token:: ', result.access_token)
                  return result.access_token
              });
        })
  })
  .then(() =>
      VoxeetSDK.session.open({name: randomName})
        .then(() => {
            enableUI('test-conference')
        })
  )
```

**Comment by allvoice-devteam** [comment]
thank you for your support.

hope document https://dolby.io/developers/interactivity-apis/client-sdk/initializing provides the same.

**Comment by FabienLavocat** [comment]
Does it work as expected with the `return`? I'll make sure we update the documentation! Thanks!

**Comment by allvoice-devteam** [comment]
yes It works right after I added `return` to callback function itself.
and also recieved a wrong code at https://support.dolby.io/hc/en-au/requests/1123 

thnx

**Comment by FabienLavocat** [comment]
Excellent news! I'll close the support ticket and I requested the documentation to be updated. Thank you.
