### ISSUE TITLE
StopAudio() and conference.mute()

### ISSUE THREAD

**Issue by kunal13053** [dolbyio-samples/comms-sdk-web-getting-started#16]
My app contains a functionality to mute other participants. Currently to do this, I am using conference.mute() along with ably events to allow participants to mute other remote participant. I want to use StopAudio() to achieve this, because it works for remote participant as well. But stopAudio() fails in the case when I have already switched off the video and then use stopAudio() to mute other remote participant. In this case, the participant is removed from the conference. How can I use stopAudio() to mute a remote participant?

**Comment by FabienLavocat** [comment]
Hi @kunal13053, what do you mean by “removed from the conference”?

In the getting started application (if Dolby Voice is off), you can turn off both audio and video for a participant. This will remove the DOM element that represents the participant but (s)he is still in the conference.

**Comment by kunal13053** [comment]
I was able to get it working by using just stopAudio(). I completely removed my implementation of using conference.mute() in the ably channels. It's working fine now. Thanks!
