### ISSUE TITLE
Smartphone crash

### ISSUE THREAD

**Issue by cataneno** [dolbyio-samples/comms-sdk-web-getting-started#2]
I tested succesfully web app on several desktop browser and omobile device, but i'm not able to run it on hauawei and honor smarthphone using Chrome. This is the stacktrace of the error:
webrtc VoxeetRTC.setRemoteDescription error:  b38e3e05-f2cb-30e4-9358-2e211cfb6be7 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters.
error @ logging.js:28
(anonymous) @ VoxeetRTCNative.js:286
s @ VoxeetRTCNative.js:5
Promise.then (async)
u @ VoxeetRTCNative.js:6
(anonymous) @ VoxeetRTCNative.js:7
Je @ VoxeetRTCNative.js:3
(anonymous) @ VoxeetRTCNative.js:281
(anonymous) @ VoxeetRTCNative.js:281
(anonymous) @ VoxeetRTCNative.js:7
Je @ VoxeetRTCNative.js:3
setRemoteDescription @ VoxeetRTCNative.js:278
(anonymous) @ VoxeetRTCBase.js:28
o @ VoxeetRTCBase.js:4
Promise.then (async)
u @ VoxeetRTCBase.js:6
o @ VoxeetRTCBase.js:4
Promise.then (async)
u @ VoxeetRTCBase.js:6
(anonymous) @ VoxeetRTCBase.js:7
Ce @ VoxeetRTCBase.js:3
addPeer @ VoxeetRTCBase.js:25
(anonymous) @ ConferenceManager.ts:140
Promise.then (async)
onInitialized @ ConferenceManager.ts:138
(anonymous) @ ConferenceManager.ts:52
Promise.then (async)
init @ ConferenceManager.ts:52
(anonymous) @ ConferenceService.ts:192
o @ ConferenceService.ts:10
Promise.then (async)
u @ ConferenceService.ts:12
(anonymous) @ ConferenceService.ts:13
Dt @ ConferenceService.ts:9
_join @ ConferenceService.ts:183
(anonymous) @ ConferenceService.ts:179
(anonymous) @ ConferenceService.ts:13
Dt @ ConferenceService.ts:9
join @ ConferenceService.ts:178
(anonymous) @ ui.js:17
Promise.then (async)
joinButton.onclick @ ui.js:17
logging.js:28 webrtc Failed to join conference RemoteDescriptionError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters.
    at https://unpkg.com/@voxeet/voxeet-web-sdk@2.1.1/dist/voxeet-sdk.js:203:77752
    at ut.<anonymous> (https://unpkg.com/@voxeet/voxeet-web-sdk@2.1.1/dist/voxeet-sdk.js:203:77798)
    at Generator.throw (<anonymous>)
    at s (https://unpkg.com/@voxeet/voxeet-web-sdk@2.1.1/dist/voxeet-sdk.js:203:71712)
error @ logging.js:28
(anonymous) @ ConferenceManager.ts:155
Promise.catch (async)
onInitialized @ ConferenceManager.ts:153
(anonymous) @ ConferenceManager.ts:52
Promise.then (async)
init @ ConferenceManager.ts:52
(anonymous) @ ConferenceService.ts:192
o @ ConferenceService.ts:10
Promise.then (async)
u @ ConferenceService.ts:12
(anonymous) @ ConferenceService.ts:13
Dt @ ConferenceService.ts:9
_join @ ConferenceService.ts:183
(anonymous) @ ConferenceService.ts:179
(anonymous) @ ConferenceService.ts:13
Dt @ ConferenceService.ts:9
join @ ConferenceService.ts:178
(anonymous) @ ui.js:17
Promise.then (async)
joinButton.onclick @ ui.js:17
ui.js:25 Something wrong happened : RemoteDescriptionError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters.

Can you help me to solve it? Thanks

**Comment by FabienLavocat** [comment]
Please reopen if you still have the problem with the latest version.
