### ISSUE TITLE
Screen Sharing Bug

### ISSUE THREAD

**Issue by jmw11x** [dolbyio-samples/comms-sdk-web-getting-started#32]
This feature only works for items within the tabs. Nothing happens when I share another window or ***EDIT A DIFFERENT*** browser.

**Comment by jmw11x** [comment]
Here is error

Exception: Permission denied by system
(anonymous) @ ui.js:131

**Comment by jmw11x** [comment]
the pop up comes up, the tabs are there for tab window full screen. The screen is shown in the tabs, but when you click screen share nothing happens the button stays the same as before pressing it and the stop screen share is still greyed out.

**Comment by FabienLavocat** [comment]
Thank you for reporting this issue @jmw11x , like the error message is saying `Exception: Permission denied by system` it looks like your Web Browser does not have the system permissions to share the entire screen (nor the browser). Could you please give me some details, what OS as you using, are you on Chrome / Edge / Safari / Firefox? I will give you the steps to make it to work.

**Comment by jmw11x** [comment]
Sure Mac OS. It produced the same error in both Edge and Chrome. But I will note, for the project I am working on this would get use in, the client would require that It would have to work for all users without having to do anything on their part.

**Comment by jmw11x** [comment]
and thank you!

**Comment by jmw11x** [comment]
Also there was a typo in the first message, sorry about that screen share works only on tabs within the browser the page started on.

**Comment by jmw11x** [comment]
https://imgur.com/a/vu9WEbI 

Sharing settings

**Comment by FabienLavocat** [comment]
On MacOS, the OS will block by default any applications that wants to do a screen recording, for obvious privacy reasons. In your _System Settings_, go to _Privacy & Security_, then pick _Screen Recording_ and make sure Chrome / Edge... have the permissions:
![image](https://github.com/dolbyio-samples/comms-sdk-web-getting-started/assets/4154532/d6223f39-7064-40e4-a14a-4f3337064ab8)
Note: the picture you are sharing is not related to the same thing

**Comment by jmw11x** [comment]
thank you for the detailed reply. I assume that this is this going to be consistent across all os?

**Comment by FabienLavocat** [comment]
You do not need to build an app, you only need a website that can run on any web browser. All web browser on most of operating systems will require the same security & privacy setting to be turned on. On Windows it is in a different section but the idea is exactly the same.

**Comment by jmw11x** [comment]
https://imgur.com/a/YFShUNI

Still does the same thing despite changing the settings. Share entire screen or window has no response with the same permission error.

**Comment by FabienLavocat** [comment]
Did you restart Edge after setting the permissions?
Also, could you use the latest version of the SDK (3.9)
```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@voxeet/voxeet-web-sdk/dist/voxeet-sdk.js"></script>
```

**Comment by jmw11x** [comment]
You have to fully restart the computer for it to work! the message from apple that restarting browser was incorrect is all. It now works. Thanks. TO clarify what you are saying is that I will have to inform my users to enable this for the browser they are using?

Thank you so much again for the assistance.

**Comment by FabienLavocat** [comment]
Any standalone app like Zoom or MS Teams (or any other) needs to go through the exact same process and allow permissions in the System Settings. Usually the first time you try to share your screen, the app or browser will ask you to allow the capability, if you deny it, then you will have to manually go to the settings.
