### ISSUE TITLE
User invalid

### ISSUE THREAD

**Issue by alpalex** [dolbyio-samples/comms-sdk-web-getting-started#34]
### Context
* App is using Enhanced Access Control
* Backend: nodejs using dolby HTTP REST api
* Frontend: Firefox/Chrome

### Web SDK
is implemented like mentioned on https://docs.dolby.io/communications-apis/docs/getting-started-with-the-javascript-sdk

### Error
when pressing the join button an error happens:
```
webrtc Failed to join conference ServerError: User is not valid
```
it seems to be related to this HTTP call

`https://comms.sdk.dolby.io/v1/conferences/638485b8-c514-44a9-92fe-8d2828ed26b8/join`
```javascript
{
  "sync": true,
  "sdp_version": "SDP_V6",
  "user": {
    "type": "user"
  },
  "options": {
    "constraints": {
      "audio": {
        "autoGainControl": true,
        "googAutoGainControl": true,
        "noiseSuppression": true,
        "echoCancellation": true
      },
      "video": false
    },
    "mixing": {
      "enabled": false,
      "uri": "638485b8-c514-44a9-92fe-8d2828ed26b8"
    },
    "simulcast": false,
    "preferSendMono": true,
    "preferRecvMono": false,
    "forwardingStrategy": "lastSpeakerStrategy",
    "dvwc": false,
    "videoFilterOptions": {},
    "supportedAVSyncFakeAudio": true,
    "supportedSpatialAudioStyles": [
      "shared",
      "disabled",
      "individual"
    ],
    "supportedMultiScreenShare": "sendrecv"
  }
}
```
Which results in `403`
```javascript
{
  "type": "ErrorResponse",
  "error_code": 113,
  "error_reason": "invalid_cat_user",
  "error_description": "User is not valid"
}
```
**Information**
The button call triggers this
```javascript
await VoxeetSDK.conference.join({
   id: conferenceId
}, {
  conferenceAccessToken: userToken
});
```

ConferenceId and userToken comes from calling `/v2/conferences/create`. userToken is e.g. "participantA"
```javascript
{

  conferenceId: "638485b8-c514-44a9-92fe-8d2828ed26b8",

  ...

  usersTokens: {
    "participantA": "some long token"
  }
}
```

Unfortunately i have no access to the /v1/ API documentation, so i have no idea what could be the problem.
Thanks for the help

**Comment by alpalex** [comment]
just updated the information about how i call `VoxeetSDK.conference.join()`

im not calling `VoxeetSDK.conference.create()` like in the example, because i am creating the conference in my backend before hand with a different client access token

**Comment by FabienLavocat** [comment]
When you provide the conference access token back to the end user, are you certain that you provide the token for the right user? Meaning that in your example, you create a conference and get an access token for `participantA`:
```json
{
  conferenceId: "638485b8-c514-44a9-92fe-8d2828ed26b8",
  ...
  usersTokens: {
    "participantA": "some long token"
  }
}
```
But are you opening a session (client side SDK) with a user that has the external name `participantA`?
```js
await VoxeetSDK.session.open({externalId: "participantA"});
```

**Comment by alpalex** [comment]
until now i did ` VoxeetSDK.session.open("participantA");`

but i changed the code to `VoxeetSDK.session.open({externalId: "participantA"});`
and made sure it's sending the correct token (observing the http headers sent) and it still gives me the same error

**Comment by alpalex** [comment]
I also found `.fetch()` which might be what i need here but that still throws the same error

```javascript
const conference = await VoxeetSDK.conference.fetch(conferenceId)

await VoxeetSDK.conference.join(conference, {
    conferenceAccessToken: tokenOfParticipantA,
    constraints: {
        audio: true,
        video: true,
    }
});
```

**Comment by FabienLavocat** [comment]
It looks like for the conference `638485b8-c514-44a9-92fe-8d2828ed26b8` there was a problem with the user names you're using. What external ID did you use when you create the conference?

**Comment by alpalex** [comment]
not sure about that particular conference. But the latest one i created is `6c0a0409-2003-4f70-b7bb-db9aa99c14a9`
where i used `participant_1` and `participant_2`

**Comment by FabienLavocat** [comment]
I am seeing this error coming from the client SDK:
```
MediaStreamError: NotReadableError: Failed to allocate videosource
```

**Comment by alpalex** [comment]
Yeah, i force enabled video `VoxeetSDK.conference.join(conference, {constraints: {audio: true, video: true}}` but was testing from http.

That error is gone with https now, but still, always getting those "User is not valid" messages. And then the sdk just logs out (both chrome, firefox)

**Comment by FabienLavocat** [comment]
Could you share a sample app where I can reproduce the problem?

**Comment by alpalex** [comment]
sure, this will be temporarily available
[REDACTED]

it is reusing the same configuration every time you load the page

**Comment by FabienLavocat** [comment]
Oh I see the problem. You are using a Client Access Token to join the conference. The Client Access Token is only meant to be used for initializing the SDK.
When you want the user to join a conference you call the `client-config` endpoint. In that backend code, you need to request a [Client Access Token](https://docs.dolby.io/communications-apis/reference/get-client-access-token) for the client SDK to initialize, then you call the [conference create](https://docs.dolby.io/communications-apis/reference/create-conference) with the id of that participant, you will get Conference Access Token that you need to return to your client.
So the client will receive the conference ID, the client access token and the conference access token. Use the Client AT to initialize the SDK and the Conf AT to join the conference.

**Comment by alpalex** [comment]
did that change (see headers), still the error.

just to make sure: I'm scoping the client_access_token to `'session:update'` i hope that is fine


---------
Also interesting: when i tried to use conferenceAccessToken for sdk init and usersToken for conference.join, i broke something else
```json
{
  "type": "ErrorResponse",
  "error_code": 90,
  "error_reason": "Illegal argument",
  "error_description": "No enum constant com.reactive.common.model.ConferenceAccessType.Permission.ROLE_CUSTOMER"
}
```

**Comment by FabienLavocat** [comment]
I would recommend to use `notifications:set` for the client access token.

Also, replace:
```js
await joinConference(conferenceId, clientAccessToken)
```
by
```js
await joinConference(conferenceId, userToken)
```

**Comment by alpalex** [comment]
another victim of the cache...

yeah that code change is now visible and i changed the scope in the backend code, still error

**Comment by FabienLavocat** [comment]
When you [create a Client Access Token](https://docs.dolby.io/communications-apis/reference/get-client-access-token), are you setting an external ID? If not, could you set the external ID of the client.

**Comment by alpalex** [comment]
that fixed it.
What a journey. thanks for the time Fabien, highly appreciated it!
