### ISSUE TITLE
Screen share cause infinite screen loops. 

### ISSUE THREAD

**Issue by kunal13053** [dolbyio-samples/comms-sdk-web-getting-started#9]
When you do a screen share the screen for host screen goes into an infinite screen loop, something like a 2-mirror effect. This screen is then visible to all participants due to screen share. Is there a way to avoid this as this is generally a bad User experience.

**Comment by FabienLavocat** [comment]
Hi @kunal13053 What I can think of to avoid this problem is not to display the "feedback" stream to the local participant.
Instead, you can add a message in the UI saying that you are sharing the screen without showing the actual stream.

**Comment by kunal13053** [comment]
Yeah, this is one way to solve this. Thanks.
